run:
  tests: false

linters:
  enable-all: true

issues:
  exclude-use-default: false
  exclude: "Error return value of .((os\\.)?std(out|err)\\..*|.*Close|.*Flush|os\\.Remove(All)?|.*printf?|os\\.(Un)?Setenv). is not checked"
